[tool.poetry]
name = "test-llm"
version = "0.1.0"
description = ""
authors = ["wilfr <wilfredvancasteren@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.99.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
